# Generated by Django 4.2.9 on 2024-04-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'volunteers'), (3, 'beneficiaries'), (4, 'fundraiser')]),
        ),
    ]
